services:
  mongo:
    image: mongo:7
    container_name: sena-centro-formacion-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: sena
      MONGO_INITDB_ROOT_PASSWORD: sena123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
